edouardparis/lntop

README.md, docker/.gitignore, docker/build.sh, docker/clean.sh, docker/docker-compose.yml, docker/inspect.sh, docker/lntop.sh, docker/lntop/Dockerfile, docker/lntop/config.toml, docker/lntop/home/run, docker/logs.sh
Hi, nice job on lntop. 
I've added initial support for running it from docker.
I have tested it on my Ubuntu 18.10 VPS running mainnet lnd in another docker container with data folder mapped to host machine - it works fine. 
The only problem is on exit (F10). I don't think lntop is exiting cleanly. It must be forced via CTRL+C or when waiting enough it fails with
```
panic: send on closed channel
goroutine 12 [running]:
github.com/edouardparis/lntop/pubsub.(*pubSub).ticker.func1(0xc000151b90, 0xc00008f4a0, 0xc481c0, 0xc000038048, 0xc000076b40)
/go/src/github.com/edouardparis/lntop/pubsub/pubsub.go:55 +0x30a
created by github.com/edouardparis/lntop/pubsub.(*pubSub).ticker
/go/src/github.com/edouardparis/lntop/pubsub/pubsub.go:36 +0x94
```
This is probably worth a separate ticket.
=> add docker support

docker/logs.sh
now that we have the log mapped to host folder we can simply tail it there
=> docker: tail logs from host

ui/views/channels.go, ui/views/menu.go, ui/views/transactions.go
This PR fixes two issues:
1) the cursor can move past the last channel or transaction; pressing Enter when it's not positioned on a valid item causes segmentation fault
2) the cursor can be positioned after the last channel/tx column; trying to sort while it's there also causes segfault
=> Constrain the cursor and prevent segfaults

README.md, cli/cli.go, config/config.go, config/default.go, events/events.go, network/backend/backend.go, network/backend/lnd/lnd.go, network/backend/lnd/proto.go, network/backend/mock/mock.go, network/models/routingevent.go, pubsub/pubsub.go, ui/controller.go, ui/models/models.go, ui/views/menu.go, ui/views/routing.go, ui/views/views.go
Adds ROUTING view which shows log of HTLC forwards, sends & receives. It is useful for viewing failed forwards which are (AFAIK) not persisted in lnd but can be obtained through [streaming api](https://api.lightning.community/#subscribehtlcevents). Not quite sure what the best column order & column colors are:smiley: 
Needs #21.
=> Add routing view

pubsub/ticker.go
When `lnd` restarts or stops the network requests fail as expected. They're logged but there are no nil checks later. With this fix `lntop` stays usable (even though the data is stale) until `lnd` is back online.
=> Fix segfault on network errors

network/backend/lnd/proto.go
=> routing: truncate failure detail after first line

network/backend/lnd/lnd.go, network/models/channel.go, ui/cursor/cursor.go, ui/views/channel.go, ui/views/help.go, ui/views/routing.go, ui/views/transaction.go
One thing that's been bugging me is lack of details regarding fee policies in the channel details view. It's not obvious which node is first and which is second (it's basically random). This PR fixes three things:
- policies renamed to `Outgoing` (for our side of the channels) and `Incoming` (for the opposite side that we don't control)
- our side is always displayed first because it's arguably more important
- cursor movements are restricted to the actual data lines in the detail views (channels, transactions and help) so we can't scroll past it anymore; before it was only fixed for the list views
=> Improve policies view and restrict cursor in detail views

README.md, config/default.go, ui/views/channel.go, ui/views/channels.go, ui/views/routing.go, ui/views/views.go
SCID represents the same information as channel id but uses different formatting exposing the three components (block height, transaction index, output index). LN software seems to pick one of these formats at random so I suppose it's better to support both.
=> Add short channel id columns

ui/models/sort.go, ui/views/channels.go
Some columns don't allow sorting for some reason but it's actually very useful. It's easier to find a channel by its name when they're sorted by it. Or find your oldest and newest ones (sort by the channel ID). Or group those inactive channels together. Endless possibilities!
=> Allow sorting by all columns

README.md, config/config.go, network/backend/lnd/lnd.go, network/models/channel.go, network/models/node.go, ui/views/channel.go, ui/views/channels.go, ui/views/routing.go
I have plenty of channels and not all peers have aliases set up. For private channels it's not even expected. However, if you test and use multiple non-custodial wallets that open real channels to your node you might want to know which is which and remembering the hex digits quickly becomes tedious. So I added this handy feature. Now you can force an alias for any node (including those already having an alias, just in case!) and it will be printed in cyan everywhere unlike the "real" aliases. That way you won't forget that this one comes from the config file. Adding these aliases is simple:
```
[network.aliases]
035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226 = "Wallet of Satoshi"
03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f = "-=[ACINQ]=-"
```
And …
=> Add forced aliases

README.md, config/default.go, ui/views/channels.go
I wondered why isn't there a `remote balance` column, only local and cap, so I added it. It's not just `cap - local`, the calculation is more complex and sometimes it's good to know how much is on the other side. I also added the `number of updates` column, it lets the user estimate the channel popularity and also see what channels are the candidates for reopening to prune the database in case it grows too big. `lnd` saves a distinct revocation transaction for every channel update (which includes any activity in the channel including failed HTLCs) so they might pile up with time and consume significant amount of disk space.
=> Add remote balance and update count columns

ui/models/sort.go, ui/views/channels.go
From the Go standard library description:
```go
// Sort sorts data.
// It makes one call to data.Len to determine n and O(n*log(n)) calls to
// data.Less and data.Swap. The sort is not guaranteed to be stable.
func Sort(data Interface) {
```
The sort is indeed not stable i.e. it will sort the equal elements in random order. Most elements in the grid don't suffer from that as they're all unique enough or they're not sorted by too often but `gauge` isn't one of them. It currently uses integer math to calculate the percentage and the collisions are real when the number of channels is high enough. It results in different order of channels every time you sort by the `gauge` column, a couple or sometimes three channels swap places. Doesn't look good. And sometimes those two channels have …
=> Make gauge sort more stable

ui/views/channel.go
It's useful to see the pending HTLCs sometimes, especially if they hang there for a while and you want to know when they're gonna expire. I used RTL for this purpose before but turns out adding this functionality to lntop is very trivial and they even update automatically. I also added one more space to the policy information to keep a nice one character wide border at the left.
=> Display pending HTLCs in channel view

README.md, ui/views/channels.go
This PR adds columns "BASE OUT", "RATE OUT", "BASE IN" and "RATE IN" for fee rates of the incoming and outgoing channel policy. 
I am open for suggestions about the naming of inboud/outbound base fee/fee rate so to keep the column space not too crowded.
=> #70: Display channel fees

ui/views/channels.go
Fixes a crash introduced in #72 if one or both policies are missing for any channel. It happens for new channels usually if policies aren't propagated quick enough. This PR adds checks in display and sort functions so missing policies default to zero values.
=> Fix crash on missing policies

network/backend/lnd/proto.go, network/models/channel.go, ui/views/channel.go, ui/views/summary.go
Amounts are hard to read without separators and in Bitcoin case the usual groups of three digits can be confusing because 1 BTC is 10e8 sats. Instead I implemented a better format proposed by [satcomma](https://bitcoin.design/guide/designing-products/units-and-symbols/#satcomma). It's not exactly like the link describes because I replaced spaces with commas to make it look consistent with the main screen. Most amounts like channels and HTLCs don't need the BTC point because they're usually much smaller than 1 BTC so commas are fine. Total node capacities are usually greater than 1 BTC so it's appropriate there. I currently didn't patch the other screens that show amounts because of this reason.
=> Add pretty amount formatting

network/backend/backend.go, network/backend/lnd/lnd.go, network/backend/lnd/proto.go, network/backend/mock/mock.go, network/models/node.go, ui/controller.go, ui/keybindings.go, ui/models/channels.go, ui/models/models.go, ui/views/channel.go
This PR adds the ability to see how many channels are disabled to and from your peer. It's useful to find out if the peer has a big outage or if it's just your connectivity. Basically "down for everyone or just me?". The number of disabled channels is highlighted with bold yellow if the percentage of disabled channels is between 25 and 50, and bold red if it's 50% or more.
While testing on RPi I noticed that this feature adds some inconvenience when I open a channel to a big node like ACINQ, it takes too much time to retrieve and process all those channels (around 1-1.5 seconds but still). Since this feature isn't very essential and to not degrade the overall experience I added some context magic. Now the disabled channels are only shown if this request takes less than 100 ms, otherwise …
=> Show disabled channel count for node

events/events.go, network/backend/backend.go, network/backend/lnd/lnd.go, network/backend/lnd/proto.go, network/backend/mock/mock.go, network/models/channel.go, pubsub/pubsub.go, ui/controller.go, ui/models/channels.go, ui/models/models.go, ui/views/channel.go, ui/views/channels.go
This PR fixes a couple of annoyances:
1. New channels displayed incoming/outgoing policies wrong due to outdated information. Now these policies are fetched on every channel update if any of them is `nil`. This should only happen when the channel is very new and the policy information isn't well propagated. It won't result in a big gRPC request inefficiency.
2. Closed (fully resolved) channels are now marked as such explicitly. It's possible to delete these channels when they're closed but it might be confusing so I decided to add a new channel status `closed` instead and mark all channels that aren't present in the `listchannels` result as closed. Additionally I added channel status subscription, there was such a function already but its implementation was mostly commented out so I …
=> Show closed and disabled channels, fix policy order

cli/cli.go, ui/ui.go
This PR seeks to address issue https://github.com/edouardparis/lntop/issues/77 by closing the events channel in the main client routing `cli.Run` after all subroutines exited.
=> Fix prematurely closing events channel

ui/models/channels.go
The maturity field added in #92 isn't updated when the channel is updated. Because of that it's useless since it shows a stale number that should update on every block to be useful. This PR fixes it.
=> Update channel maturity

ui/views/routing.go
When deleting the ROUTING view, every sub-view are being deleted. gocui returns ErrUnknownView if the view was not created, we can safely ignore this error.
=> fix: check UnknownView error in routing delete method
